server:
  port: 2020

spring:
  application:
    name: task-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/magazine
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret=secret: